"""empty message

Revision ID: 286ab929b01d
Revises: 70ac4a366e17
Create Date: 2019-09-25 03:21:36.587168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286ab929b01d'
down_revision = '70ac4a366e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###
